# -*- coding: utf-8 -*-
"""Pertemuan 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18XMpjfSjgP5kAQO0DegNT8qWAL4A_kyk
"""

# Program biodata mahasiswa
# Membuat variable beserta isinya (nilainya)
NIM = 4623
nama = 'Irfiyanda Abidin'
alamat = 'Pemalang'
jenis_kelamin = 'Laki laki'
tempat_lahir = 'Pemalang'
tanggal_lahir = '08 April 2003'
# Mencetak isi variable
print('NIM \t\t: ', NIM)
print('Nama \t\t: ', nama)
print('Alamat \t\t: ', alamat)
print('Jenis Kelamin \t: ', jenis_kelamin)
print('Tempat lahir \t: ', tempat_lahir)
print('Tanggal lahir \t: ', tanggal_lahir)


a= int(input("Masukan nilai a: "))
b= int(input('Masukan nilai b: '))
c= a/b
print('Hasil %d / %d = %d' % (a,b,c))