# -*- coding: utf-8 -*-
"""Pertemuan 6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1alqgvhS7fUSPy6OKeK7TbPi-7LszZF3a
"""

# Praktik ke 1
jawab = 'ya'
hitung = 0
while(jawab == 'ya'):
  hitung += 1
  jawab = input("Ulang lagi tidak? ")
print ("Total perulangan: ", hitung)

# Praktik ke 2
count = 0
while (count < 100):
  print("Jumlah adalah: ", count)
  count = count + 1
print("Selamat tinggal")

# Praktik ke 3
ulang = 100
for i in range(ulang):
  print ("Perulangan ke-" + str(i))

# Praktik ke 4
item = ['kopi', 'nasi', 'teh', 'jeruk']
for isi in item:
  print(isi)

# Praktik ke 5
i = 0
while i < 5:
  j = 0
  while j < 5:
    print('A', end=' ')
    j = j + 1
  print('B\t')
  i = i + 1

# Praktik ke 5
for i in range (0,5):
  for j in range (0,5):
    print("A", end=" ")
  print("B\t")

# Praktik ke 6
nilai = [80, 67, 75, 83, 90, 65]
min = nilai[0]
max = nilai[0]
avg = 0
count = 0
total = 0
for i in nilai:
  count = count + 1
  if min > i:
    min = i
  if max < i:
    max = i
  total = total + i
print ('minimal: ', min)
print ('maksimal: ', max)
print ('rata rata: ', (total/count))