# -*- coding: utf-8 -*-
"""Pertemuan 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/133Dg2KB3KUWCq2UkWd2B89-srZXAjMmR

**Algoritma:**
1. Mulai
2. Tentukan nilai panjang dan simpan pada variabel p.
3. Tentukan nilai lebar dan simpan pada variabel l.
4. Tentukan nilai tinggi dan simpan pada variabel t.
5. Hitung luas balok yang disimpan pada variabel luas dengan proses berikut:
6. luas = (2 x p x l) + (2 x p x t) + (2 x l x t)
7. Hitung volume balok yang disimpan pada variabel volume dengan proses berikut:
8. volume = p x l x t
9. Tampilkan nilai luas.
10. Tampilkan nilai volume.
11. Selesai.
"""

p = 10
l = 20
t = 10
luas = (2*p*l) + (2*p*t) + 2*l*t
volume = p * l *t
print('Luas balok : ', luas)
print('Volume balok : ', volume)

p_string = input('Masukan Panjang : ')
p = int(p_string)
l_string = input('Masukan Lebar : ')
l = int(l_string)
t_string = input('Masukan Tinggi : ') 
t = int(t_string)
luas = (2*p*l) + (2*p*t) + 2*l*t
volume = p * l *t
print('Luas balok : ', luas,'cm2')
print('Volume balok : ', volume,'cm3')

"""**Soal:**

Terdapat suhu dalam satuan Celcius yaitu 40'C . Suhu ini akan dikonversi ke dalam Fahrenheit
(F), Reamur (R), dan Kelvin (K) dimana rumus konversi tersebut adalah sebagai berikut:

F = C * 9 / 5 + 32

R = C * 4 /5

K = C + 273.5

Susunlah algoritma, Flowchart, dan kode program untuk membangun program komputer konversi
suhu Celcius ke Fahrenheit, Reamur, dan Kelvin!

**Algoritma**
1. Mulai
2. Tentukan nilai celciusnya 40
3. Konversikan ke Fahrenheit, Reamur, Kelvin dengan rumus berikut:
4. Fahrenheit = Celcius*9/5+32
5. Reamur = Celcius*4/5
6. Kelvin = Celcius*273.5
7. Tampilkan nilai F, R dan K
"""

Celcius = 40
Fahrenheit = Celcius*9/5+32
Reamur = Celcius*4/5
Kelvin = Celcius*273.5
print(Fahrenheit)
print(Reamur)
print(Kelvin)

"""**Algoritma**
1. Mulai
2. Tentukan nilai celciusnya
3. Konversikan ke Fahrenheit, Reamur, Kelvin dengan rumus berikut:
4. Fahrenheit = Celcius*9/5+32
5. Reamur = Celcius*4/5
6. Kelvin = Celcius*273.5
7. Tampilkan nilai F, R dan K


"""

Celcius_string = input('Masukan berapa suhu yang akan dikonversi (satuan Celcius) : ')
C = int(Celcius_string)
Fahrenheit_string = C*9/5+32
F = int(Fahrenheit_string)
Reamur_string = C*4/5
R = int(Reamur_string)
Kelvin_string = C*273.5
K = int(Kelvin_string)
print("===========< Berikut Hasil Konversinya >=========")
print(C, 'Celcius','Setara dengan', F, 'F')
print(C, 'Celcius','Setara dengan',R, 'R')
print(C, 'Celcius', 'Setara dengan', K, 'K')