# -*- coding: utf-8 -*-
"""Pertemuan 7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KRUBRCrgk8s2mgRk5M0ejqeBwXLH_r6f
"""

# Praktik ke 1
for i in range (0,5):
  for j in range (0,5):
    print(' i: ', i, ' j: ', j, ' ', end='')
  print()

# Praktik ke 2
for i in range (0,5):
  for j in range (0,5):
    if (i <= j):
      print('*', end=' ')
    else:
      print(' ', end=' ')
  print()

# Praktik ke 3
def hello():
  print('Hello World!')

def tambah (a, b):
  return a+b;

h = tambah(5, 7)
x = hello()

# Praktik ke 4
def hasil_bagi(a=4, b=3):
  return a%b

x = hasil_bagi(b=2, a=4)
print(x)

# Praktik ke 5
def fToC(f):
  c=(f-32)/9 * 5
  return c

h = fToC(212)
print(h)

# Praktik ke 6
def counter(start=0, step=1):
  x = [start]
  def _inc():
    x[0] += step
    return x[0]
  return _inc

c1 = counter()
c2 = counter(100, -10)
a = c1()
b = c2()
print(a)
print(b)