# -*- coding: utf-8 -*-
"""Pertemuan9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pVaVVXhF_DFVpjHs4zSDd5dgb1oV6Tli
"""

# Deklarasi List sederhana
# Indeks  0 1 2 3 4 5
list_angka  = [76,65,43,78,96,25]
list_string = ['Apel', 'Belimbing', 'Chery', 'Durian']
list_campuran = ['A','B', 5, 7, 6]
# Menampilkan list
print('list angka: \n', list_angka)
print('list string: \n', list_string)
print('list campuran \n', list_campuran)

# Mengakses element list
lst = [78, 63, 47, 79, 96, 25]
print('Indeks ke-3: ', lst[3])
print('Menampilkan sejumlah sampai indeks < 4', lst[:4])
print('Menampilkan mulai indek ke-2: ', lst[2:])
print('Menampilkan mulai indeks ke-2 sampai indeks < 5: ', lst[2:5])
print('Menampilkan keseluruhan: ', lst[:])
print('Mengakses dengan perulangan: ')
for i in lst:
  print(i)

# Operasi pada list 
buah = ['Apel','Belimbing', 'Chery', 'Durian']

print('\nMenambahkan item: ')
buah.append('Jambu')
print(buah)

print('\nMenghapus item: ')
del buah[2]
print(buah)

print('\nMenyisipkan item: ')
buah.insert(1, 'Nanas')
print(buah)

print('\nMengurutkan item secara ascending: ')
buah.sort()
print(buah)

print('\nMengurutkan item secara descanding: ')
buah.reverse()
print(buah)

print('\nMenghapus isi semua elemen: ')
buah.clear()
print(buah)

# list multi dimensi
# list dengan dimensi 3x3
arr = [
       [34, 67, 78],
       [23, 45, 56],
       [11, 18, 74]
]
print ('Mengakses indeks (1,2): ', arr[1][2])
print ('Mengakses dengan perulangan: ')
for a in arr:
  for b in a:
    print(b, end= " ")
  print()

barang = [] # Variabel kosong untuk di isi list

def daftar_barang(): # Fungsi untuk menampilkan daftar barang
  if len(barang) <= 0:
    print("\nTidak ada barang")
  else:
    for i in range(len(barang)):
      print("[%d] %s" % (i, barang[i]))

def tambah_barang(): # Fungsi untuk menambah objek pada variabel barang
  tambah = input("Masukkan nama barang: ")
  barang.append(tambah)

def ubah_barang(): # Fungsi untuk mengubah atau mengedit objek yang sudah ada pada variabel barang
  if len(barang) <= 0:
    print("Belum ada barang")
  elif len(barang) >= 1:
    ubah_id = input("Masukan ID barang: ")
    ubah_id = int(ubah_id)
    if ubah_id > len(barang) or ubah_id < len(barang):
      print("Salah input")
    else:
      ubah_nama = input("Masukan nama barang baru: ")
      barang [ubah_id] = (ubah_nama)
  else:
    print("Salah input")
  
def hapus_barang(): # Fungsi untuk menghapus objek pada variabel barang
  if len(barang) < 0:
    print('Belum ada data')
  elif len(barang) >= 0:
      hapus = input("Pilih ID barang yang akan dihapus")
      hapus = int(hapus)
      if hapus in range (len(barang)):
        del barang[hapus]
      else:
        print("ID salah")

def menu(): # Fungsi untuk menampilkan menu sekaligus untuk memilih menu mana yang akan di panggil
  print("\n ","="*40)
  print("1. Daftar barang.")
  print("2. Tambah barang.")
  print("3. Ubah barang.")
  print("4. Hapus barang.")
  list_menu = input("\n Pilihan perintah [1,2,3,4] -> ")
  list_menu = int(list_menu)
  if list_menu == 1:
    daftar_barang()
  elif list_menu == 2:
    tambah_barang()
  elif list_menu == 3:
    ubah_barang()
  elif list_menu == 4:
    hapus_barang()
  else:
    print('salah input')

while (True):
  menu()