# -*- coding: utf-8 -*-
"""pertemuan12.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lT16i5h_x00Sk0yFJ1VCOg1iFG_cY-NE
"""

class Kendaraan:
  __nama = '-'
  __merk = '@'
  __roda = 2
  @property
  def nama(self):
    return self.__nama
  @nama.setter
  def nama(self,nama):
    self.__nama = nama
  @property
  def merk(self):
    return self.__merk
  @merk.setter
  def merk(self,merk):
    self.__merk = merk
  @property
  def roda(self):
    return self.__roda
  @roda.setter
  def roda(self,roda):
    self.__roda = roda
  
  def melaju(self):
    print(f"{self.nama} {self.merk} sedang melaju")

angkutan = Kendaraan()
angkutan.nama = "Bus"
angkutan.merk = "Hino"
opt = f"""
Detail Kendaraan:
nama \t: {angkutan.nama}
merk \t: {angkutan.merk}
"""
print(opt)

misal = Kendaraan()
print(misal.nama)

class Mobil(Kendaraan):
  __interior = None
  def __init__(self, interior = None):
    self.__interior = interior
  @property
  def interior(self):
    return self.__interior
  @interior.setter
  def nama(self, interior):
    self.__interior = interior
  def menyalip(self):
    print(f"{self.nama} {self.merk} sedang menyalip")
  
avanza = Mobil()
avanza.nama = "Grand Avanza"
avanza.merk = "Toyota"
avanza.menyalip()
avanza.melaju()

class Truk(Kendaraan):
  __bak_pangku = None
  def __init__(self, bak_pengangkut = None):
    self.__bak_pengangkut = bak_pengangkut
  @property
  def bak_pengangkut(self):
    return self.__bak_pengangkut
  @bak_pengangkut.setter
  def nama(self, bak_pengangkut):
    self.__bak_pengangkut = bak_pengangkut
  def mengangkut(self):
    print(f"{self.nama} {self.merk} sedang mengangkut material")

delta = Truk()
delta.nama = "Delta"
delta.merk = "Daihatsu"
delta.mengangkut()
delta.melaju()

class PickUp(Mobil, Truk):
  __dashboard = None
  def __init__(self, dashboard = None):
    self.__dashboard = dashboard
  @property
  def dashboard(self):
    return self.__dashboard
  @dashboard.setter
  def nama (self,dashboard):
    self.__dashboard = dashboard
  
  # contoh polimorfisme
  def mengangkut(self):
    print(f"{self.nama} {self.merk} sedang mengangkut sayuran")

nissan = PickUp()
nissan.nama = "Nissan"
nissan.merk = "Merk_Nissan"
nissan.mengangkut()
nissan.melaju()
nissan.menyalip()

