# -*- coding: utf-8 -*-
"""Pertemuan10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Cxq3X4oDn-KMkyHTGHm7PVdLxlWfqXK0
"""

class MyClass:
  i=12345
  def __init__(self):
    print('Kelas Terbentuk')
  def hello(self):
    return 'Hello World'

c = MyClass()
print(c.hello())

class Barang:
  def __init__(self, kode, nama, harga=0):
    self.kode = kode 
    self.nama = nama
    self.harga = harga
  def detail_barang(self):
    detail = f"""
    kode \t: {self.kode}\n
    nama \t: {self.nama}\n
    harga \t: {self.harga:,}\n
    """
    print(detail)

monitor = Barang('K01', 'Monitor')
monitor.harga = 50000
keyboard = Barang('K02', 'Keyboard', 25000)
monitor.detail_barang()
keyboard.detail_barang()

class Keranjang:
  def __init__(self, barang=[], keterangan=''):
    self.barang = barang
    self.keterangan = keterangan
  def daftar_belanja(self):
    for b in self.barang:
      b.detail_barang()
      print(30*'=',)

kr = Keranjang()
kr.barang.append(Barang('B01', 'Deterjen', 5000))
kr.barang.append(Barang('B02', 'Sikat Gigi', 7500))
kr.barang.append(Barang('B03', 'Minyak Goreng', 25000))
kr.daftar_belanja()
print(50*'v')
del kr.barang[1]
kr.daftar_belanja()
print(50*'v')
kr.barang[0].nama = 'Kopi'
kr.daftar_belanja()



class Karyawan:
  def __init__ (self, id=0, nama='', alamat='', jenis_kelamin=None, no_telepon=''):
    self.id = id
    self.nama = nama
    self.alamat = alamat
    self.jenis_kelamin = jenis_kelamin
    self.no_telepon = no_telepon

  def hitung_gaji(self, jam_lembur=0):
    gaji_pokok = 1000000
    return gaji_pokok + (jam_lembur * 10000)

  def presensi(self):
    print(f'{self.id} {self.nama} melakukan presensi')
  
wanto = Karyawan()
wanto.id = 756
wanto.nama = 'Wanto sujono'

wanto.presensi()
gaji = wanto.hitung_gaji(5)
print(f'gaji {wanto.id} {wanto.nama}: Rp {gaji:,}.00')

class divisi:
  def __init__(self, kode=[''], divisi=['']):
    self.kode = kode
    self.divisi = divisi
  def tampilkan_divisi(self):
    tampilkan = f"""
    Kode \t: {self.}
    """
  def daftar_divisi(self):
    for i in self.kode:
      i.