# -*- coding: utf-8 -*-
"""Pertemuan 5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XomkFSrbuEJMIUtMkii18kU8n28-W5Ua
"""

## Praktik ke 1
nilai = 9

## jika kondisi benar / TRUE maka program akan mengeksekusi perintah dibawahnya
if(nilai > 7):
  print("Selamat Anda Lulus")

## Jika kondisi salah / FALSE maka program tidak akan mengeksekusi perintah dibawah
if(nilai > 10):
  print("Selamat Anda Lulus")

## Praktek ke 2

umur = int(input("Masukkan angka: "))
if umur >= 18:
  print("Sudah beranjak dewasa")
else:
  print("Masih dibawah umur")

## Praktek ke 3

print("Masukkan dua buah angka..")
print("Dan Anda akan check hubungan kedua angka tersebut")
angka1 = input("Masukkan angka pertama: ")
angka1 = int(angka1)
angka2 = input("Masukkan angka kedua: ")
angka2 = int(angka2)
if angka1 == angka2 :
  print(angka1, " Sama dengan ", angka2)
else:
  print(angka1, " tidak sama dengan ", angka2)

## Praktik ke 4

gaji = int(input("Masukkan gaji: "))
berkeluarga = bool(int(input("masukkan 0/1: ")))
punya_rumah = input("masukkan yes/no: ")
if gaji > 3000000:
  print("Gaji sudah diatas UMR")
  if berkeluarga:
    print("Wajib ikutan asuransi dan menabung untuk pensiun")
  else:
    print("Tidak perlu ikutan asuransi")
  if punya_rumah == "yes":
    print("Wajib bayar pajak rumah")
  else:
    print("Tidak wajib bayar pajak rumah")
else:
  print("Gaji belum UMR")

## Praktik ke 5

hari_ini = "Minggu"

if (hari_ini == "Senin"):
  print("Saya akan kuliah")
elif(hari_ini == "Selasa"):
  print("Saya akan kuliah")
elif(hari_ini == "Rabu"):
  print("Saya akan kuliah")
elif(hari_ini == "Kamis"):
  print("Saya akan kuliah")
elif(hari_ini == "Jum'at"):
  print("Saya akan kuliah")
elif(hari_ini == "Sabtu"):
  print("Saya akan kuliah")
elif(hari_ini == "Minggu"):
  print("Saya akan libur")