# -*- coding: utf-8 -*-
"""pertemuan11.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1o0wSeXuSqM_rbIhvxreKnoZD9Uy9pX4H
"""

#atribut dengan modifier publik
class Segitiga:
  #konstruktor
  def __init__(self, alas=0, tinggi=0):
    self.alas = alas
    self.tinggi = tinggi
  
  #fungsi keliling
  def keliling(self):
    return (self.alas + self.tinggi + self.miring)
  
  #fungsi luas
  def luas(self):
    return (0.5 * self.alas * self.tinggi)

sg = Segitiga(5,12)
# sg = Segitiga()
sg.miring = 17
sg.alas = 12
sg.tinggi = 13
print(f'Keliling \t: {sg.keliling()}')
print(f'Luas \t\t: {sg.luas()}')

#atribut dengan modifier protected
class User:
  __id = 7456
  #konstruktor
  def __init__(self, username, password):
    self._username = username
    self._password = password
  
  # fungsi login
  def login(self):
    print(f'id: {self.__id} user: {self._username} telah melakukan login')

  # fungsi logout
  def logout(self):
    print(f"{self._username} telah melakukan logout")

paijo = User('paijo', 'rahasia')
print(f'User \t\t: {paijo._username} \npassword \t: {paijo._password}')
paijo.login()
paijo.logout()

class Mobil:
  __no_mesin = None
  __no_kerangka = None
  def __init__(self, nama='', merk=''):    
    self.__nama = nama
    self.__merk =merk

  # atribut dengan modifier private
  @property
  def no_mesin(self):
    return self.__no_mesin
  @no_mesin.setter
  def no_mesin(self, no_mesin):
    no_mesin = no_mesin % 100
    self.__no_mesin = no_mesin
  @property
  def no_kerangka(self):
    return self.__no_kerangka
  @no_kerangka.setter
  def no_kerangka(self, no_kerangka):
    self.__no_kerangka = no_kerangka
  @property
  def nama(self):
    return self.__nama  
  @nama.setter
  def nama(self, nama):
    self.__nama = nama
  @property
  def merk(self):
    return self.__merk
  @merk.setter
  def merk(self, merk):
    self.__merk = merk
 
car = Mobil()
car.no_mesin = 79090923
car.no_kerangka = 99723782
car.nama = 'New Avansa'
car.merk = 'Toyota'
output=f"""
nama \t\t: {car.nama}
merk \t\t: {car.merk}
no. Mesin \t: {car.no_mesin}
no. Kerangka \t: {car.no_kerangka}
"""
print(output)